"""Document table fields

Revision ID: 41f22c4d521a
Revises: 9c749913d234
Create Date: 2025-06-13 18:03:47.034033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f22c4d521a'
down_revision: Union[str, None] = '9c749913d234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE documents DROP CONSTRAINT documents_pkey')
    op.execute('ALTER TABLE documents ALTER COLUMN id DROP DEFAULT')
    op.execute('ALTER TABLE documents ALTER COLUMN id TYPE UUID USING (gen_random_uuid())')
    op.execute('ALTER TABLE documents ALTER COLUMN id SET DEFAULT gen_random_uuid()')
    op.execute('ALTER TABLE documents ADD PRIMARY KEY (id)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE documents DROP CONSTRAINT documents_pkey')
    op.execute('ALTER TABLE documents ALTER COLUMN id TYPE INTEGER USING (1)')
    op.execute('ALTER TABLE documents ALTER COLUMN id SET DEFAULT nextval(\'documents_id_seq\')')
    op.execute('CREATE SEQUENCE documents_id_seq')
    # ### end Alembic commands ###
